### ISSUE TITLE
SpeechDetectionGetLanguages API endpoint has string buffer errors

### ISSUE THREAD

**Issue by sseering** [tgraupmann/ConsoleChromeSpeechProxy#1]
The string proxied by the SpeechDetectionGetLanguages API endpoint becomes corruped by this proxy.

In the example I attached the my JSON parser throws errors at byte 2439. Though I think errors begin as early as byte 1745.

The handling of the chunked tranfer seems to be the problem. Maybe the StringBuffer is initialized/written/cleared in a wrong way?

[SpeechDetectionGetLanguages.txt](https://github.com/tgraupmann/ConsoleChromeSpeechProxy/files/2741065/SpeechDetectionGetLanguages.txt)

**Comment by tgraupmann** [comment]
This was likely a mismatch with the proxy not being used with the latest version of the Unity package. The latest updates have to been posted for version 1.9.

https://assetstore.unity.com/packages/tools/audio/webgl-speech-105831
